### PR TITLE
Fix no acceptance definition

### LINKED ISSUE #51: Payment doesn't work after successful task execution

### PR DESCRIPTION
**Pull request by filipgolem**
Fixes #51

### CODE REVIEW

**Comment by tworec** [comment]
pls change base, and merge it to `b0.2` @filipgolem 
it still does not work

File: yajsapi/rest/payment.ts [hunk 1]
```diff
@@ -35,7 +40,7 @@ export class Invoice extends yInvoice {
   }
 
   async accept(amount: number | string, allocation: Allocation) {
-    let acceptance: yap.Acceptance;
+    let acceptance: yap.Acceptance = new yAcceptance();
```
Comment (mfranciszkiewicz) [inline yajsapi/rest/payment.ts:43]: There is no need to subclass a typescript interface. Use:

```
let acceptance: yap.Acceptance = {
    totalAmountAccepted: amount.toString(),
    allocationId: allocation.id
};
```

**Comment by tworec** [comment]
it works. Just pls merge it to `b0.2` beside the `master`

**Review by mdtanrikulu — APPROVED** [review]
